name: 'my_pipeline_transformations'
version: '1.0.0'
config-version: 2

profile: 'my_postgres_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_pipeline_transformations:
    staging:
      materialized: view
    marts:
      materialized: table
