-- TODO: Implement staging transformation
-- This is a placeholder model for staging raw API data
SELECT
    forecast_id,
    location__lat AS lat,
    location__lon AS lon,
    timeline_type,
    time,
    values__altimeter_setting AS altimeter_setting,
    values__cloud_base AS cloud_base,
    values__cloud_cover AS cloud_cover,
    values__dew_point AS dew_point,
    values__evapotranspiration AS evapotranspiration,
    values__freezing_rain_intensity AS freezing_rain_intensity,
    values__humidity AS humidity,
    values__ice_accumulation AS ice_accumulation,
    values__ice_accumulation_lwe AS ice_accumulation_lwe,
    values__precipitation_probability AS precipitation_probability,
    values__pressure_sea_level AS pressure_sea_level,
    values__pressure_surface_level AS pressure_surface_level,
    values__rain_accumulation AS rain_accumulation,
    values__rain_intensity AS rain_intensity,
    values__sleet_accumulation AS sleet_accumulation,
    values__sleet_accumulation_lwe AS sleet_accumulation_lwe,
    values__sleet_intensity AS sleet_intensity,
    values__snow_accumulation AS snow_accumulation,
    values__snow_accumulation_lwe AS snow_accumulation_lwe,
    values__snow_intensity AS snow_intensity,
    values__temperature AS temperature,
    values__temperature_apparent AS temperature_apparent,
    values__uv_health_concern AS uv_health_concern,
    values__uv_index AS uv_index,
    values__visibility AS visibility,
    values__wind_direction AS wind_direction,
    values__wind_gust AS wind_gust,
    values__wind_speed AS wind_speed,
    _dlt_load_id,
    _dlt_id
FROM {{ source('raw', 'tomorrow__weather_forecasts') }}
