name: 'forecaster'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: []
test-paths: []
seed-paths: []
macro-paths: ["macros"]
snapshot-paths: []

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  forecaster:
    2_staging:
      schema: staging
      materialized: view
    3_marts:
      schema: marts
      materialized: table
