name: 'my_pipeline_transformations'
version: '1.0.0'
config-version: 2

profile: 'my_postgres_profile'

model-paths: ["models"]
analysis-paths: []
test-paths: []
seed-paths: []
macro-paths: []
snapshot-paths: []

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_pipeline_transformations:
    staging:
      materialized: view
    marts:
      materialized: table
